name: Python Flask Application

on:
  push:
    branches: [ main ]
    
jobs:
  build:
      
      runs-on: ubuntu-latest
      
      steps:
      
        - uses: actions/checkout@v1
        - name: build and push image
          run: |
            echo: "$ {{ secrets.DOCKERPW }}" | docker login -u "alagurajausili" --password-Rajammal_1234
            docker image build -t alagurajausili/flaskapp:v1
            docker push alagurajausili/flaskapp:v1
        
